# Generated by Django 5.1.6 on 2025-02-22 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer_db", "0007_doctors_provinces_patients_admissions_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Admissions",
            new_name="Admission",
        ),
        migrations.RenameModel(
            old_name="Customers",
            new_name="Customer",
        ),
        migrations.RenameModel(
            old_name="Doctors",
            new_name="Doctor",
        ),
        migrations.RenameModel(
            old_name="Orders",
            new_name="Order",
        ),
        migrations.RenameModel(
            old_name="Patients",
            new_name="Patient",
        ),
        migrations.RenameModel(
            old_name="Products",
            new_name="Product",
        ),
        migrations.RenameModel(
            old_name="Provinces",
            new_name="Province",
        ),
    ]
